### ISSUE TITLE
Incompatible shapes: [32,24] vs. [27,24]

### ISSUE THREAD

**Issue by guotong1988** [harsh19/Shakespearizing-Modern-English#1]
pointer_model have this problem.
I edit to python3 and tensorflow1.13. Thank you
@harsh19 
```
/data4/tong.guo/Py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
USAGE: 

python mt_main.py train <num_of_iters> <model_name>
OR
python mt_main.py inference <saved_model_path> <greedy/beam>
OR
python mt_main.py debug
OR 
python mt_main.py preprocessing


PARAMS:
 --  embeddings_dim  =  192
 --  lstm_cell_size  =  192
 --  max_input_seq_length  =  25
 --  max_output_seq_length  =  24
 --  batch_size  =  32
 --  pretrained_embeddings  =  True
 --  share_encoder_decoder_embeddings  =  True
 --  use_pointer  =  True
 --  pretrained_embeddings_path  =  ../../data/embeddings/retrofitted_external_192_startend.p
 --  pretrained_embeddings_are_trainable  =  False
 --  use_additional_info_from_pretrained_embeddings  =  True
 --  max_vocab_size  =  12000
 --  do_vocab_pruning  =  True
 --  use_reverse_encoder  =  True
 --  use_sentinel_loss  =  False
 --  lambd  =  2.0
 --  use_context_for_out  =  True
mode =  train
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  padword
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  sentstart
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  sentend
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  unk
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  ,
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  .
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  the
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  i
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  and
No pretrained embedding for (only first 10 such cases will be printed. other prints are suppressed)  you
optimizer_typ, learning_rate=  adam 0.001
===================================================
------------------------------------------------------------------------------------------------------------------------------------------- 
WARNING:tensorflow:From /data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py:45: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-03-26 17:03:39.917997: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-26 17:03:40.473149: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x9e53a20 executing computations on platform CUDA. Devices:
2019-03-26 17:03:40.473205: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-03-26 17:03:40.476009: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294620000 Hz
2019-03-26 17:03:40.705133: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x9f955d0 executing computations on platform Host. Devices:
2019-03-26 17:03:40.705219: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-26 17:03:40.705698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:15:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-03-26 17:03:40.705732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-26 17:03:40.708850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-26 17:03:40.708875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-26 17:03:40.708885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-03-26 17:03:40.709195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10802 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:15:00.0, compute capability: 3.7)
============== 
 Printing all trainainble variables
<tf.Variable 'RNN/basic_lstm_cell/kernel:0' shape=(384, 768) dtype=float32_ref>
<tf.Variable 'RNN/basic_lstm_cell/bias:0' shape=(768,) dtype=float32_ref>
<tf.Variable 'rev_encoder/basic_lstm_cell/kernel:0' shape=(384, 768) dtype=float32_ref>
<tf.Variable 'rev_encoder/basic_lstm_cell/bias:0' shape=(768,) dtype=float32_ref>
<tf.Variable 'decoder/winit:0' shape=(192, 192) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/w_out:0' shape=(192, 33583) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/b_out:0' shape=(33583,) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/w_context_out:0' shape=(192, 33583) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/b_context_out:0' shape=(33583,) dtype=float32_ref>
<tf.Variable 'decoder/RNN/sentinel_vector:0' shape=(192,) dtype=float32_ref>
<tf.Variable 'decoder/RNN/watt:0' shape=(192, 192) dtype=float32_ref>
<tf.Variable 'decoder/RNN/batt:0' shape=(1, 192) dtype=float32_ref>
<tf.Variable 'decoder/RNN/basic_lstm_cell/kernel:0' shape=(576, 768) dtype=float32_ref>
<tf.Variable 'decoder/RNN/basic_lstm_cell/bias:0' shape=(768,) dtype=float32_ref>
==================
2019-03-26 17:03:48.127902: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Traceback (most recent call last):
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,24] vs. [27,24]
	 [[{{node gradients/decoder/Mul_grad/BroadcastGradientArgs}}]]
	 [[{{node decoder/RNN/Reshape_33}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mt_main.py", line 205, in <module>
    main()
  File "mt_main.py", line 164, in main
    rnn_model.trainModel(config=params, train_feed_dict=train_buckets, val_feed_dct=val, reverse_vocab=preprocessing.idx_to_word, do_init=True)
  File "/data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_solver.py", line 159, in trainModel
    sess.run(train_op, feed_dict=feed_dict_cur )
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,24] vs. [27,24]
	 [[node gradients/decoder/Mul_grad/BroadcastGradientArgs (defined at /data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_solver.py:61) ]]
	 [[node decoder/RNN/Reshape_33 (defined at /data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py:202) ]]

Caused by op 'gradients/decoder/Mul_grad/BroadcastGradientArgs', defined at:
  File "mt_main.py", line 205, in <module>
    main()
  File "mt_main.py", line 163, in main
    _ = rnn_model.getModel(params, mode='train',reuse=False, buckets=buckets)
  File "/data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_solver.py", line 61, in getModel
    grads = tf.gradients(cost, tf.trainable_variables())
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 940, in _MulGrad
    rx, ry = gen_array_ops.broadcast_gradient_args(sx, sy)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 750, in broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'decoder/Mul', defined at:
  File "mt_main.py", line 205, in <module>
    main()
[elided 0 identical lines from previous traceback]
  File "mt_main.py", line 163, in main
    _ = rnn_model.getModel(params, mode='train',reuse=False, buckets=buckets)
  File "/data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_solver.py", line 49, in getModel
    pred = self.model_obj.getDecoderModel(config, encoder_outputs, is_training=True, mode='training', reuse=reuse, bucket_num=bucket_num)
  File "/data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py", line 411, in getDecoderModel
    cost = tf.multiply(cost, masker)  # both masker and cost is N,timesteps.
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 248, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5860, in mul
    "Mul", x=x, y=y, name=name)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [32,24] vs. [27,24]
	 [[node gradients/decoder/Mul_grad/BroadcastGradientArgs (defined at /data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_solver.py:61) ]]
	 [[node decoder/RNN/Reshape_33 (defined at /data4/tong.guo/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py:202) ]]

```

**Comment by guotong1988** [comment]
it happens at the last batch of `sess.run`

**Comment by harsh19** [comment]
Hi, 
Thank you for showing interest in our work.
Code was written for Tensorflow version 1.1.0 - Please use Tensorflow version 1.1.0 to run the code.

**Comment by parastooFalakaflaki** [comment]
Hello. I am using tensorflow version 1.1.0 but got the exact same error in the pointer_model. Thank you

 

Printing all trainainble variables
<tf.Variable 'RNN/basic_lstm_cell/weights:0' shape=(384, 768) dtype=float32_ref>
<tf.Variable 'RNN/basic_lstm_cell/biases:0' shape=(768,) dtype=float32_ref>
<tf.Variable 'rev_encoder/basic_lstm_cell/weights:0' shape=(384, 768) dtype=float32_ref>
<tf.Variable 'rev_encoder/basic_lstm_cell/biases:0' shape=(768,) dtype=float32_ref>
<tf.Variable 'decoder/winit:0' shape=(192, 192) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/w_out:0' shape=(192, 21584) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/b_out:0' shape=(21584,) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/w_context_out:0' shape=(192, 21584) dtype=float32_ref>
<tf.Variable 'decoder/decoder_output/b_context_out:0' shape=(21584,) dtype=float32_ref>
<tf.Variable 'decoder/RNN/sentinel_vector:0' shape=(192,) dtype=float32_ref>
<tf.Variable 'decoder/RNN/watt:0' shape=(192, 192) dtype=float32_ref>
<tf.Variable 'decoder/RNN/batt:0' shape=(1, 192) dtype=float32_ref>
<tf.Variable 'decoder/RNN/basic_lstm_cell/weights:0' shape=(576, 768) dtype=float32_ref>
<tf.Variable 'decoder/RNN/basic_lstm_cell/biases:0' shape=(768,) dtype=float32_ref>

Traceback (most recent call last):
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [32,25] != values[1].shape = [27,25]
	 [[Node: decoder/RNN/stack_3 = Pack[N=2, T=DT_INT32, axis=2, _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/RNN/Tile_3, _recv_token_lookup_sequences0_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mt_main.py", line 206, in <module>
    main()
  File "mt_main.py", line 165, in main
    rnn_model.trainModel(config=params, train_feed_dict=train_buckets, val_feed_dct=val, reverse_vocab=preprocessing.idx_to_word, do_init=True)
  File "/home/parastoo/Desktop/formality/Shakespearizing-Modern-English-master/code/main/mt_solver.py", line 160, in trainModel
    sess.run(train_op, feed_dict=feed_dict_cur )
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [32,25] != values[1].shape = [27,25]
	 [[Node: decoder/RNN/stack_3 = Pack[N=2, T=DT_INT32, axis=2, _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/RNN/Tile_3, _recv_token_lookup_sequences0_0)]]

Caused by op 'decoder/RNN/stack_3', defined at:
  File "mt_main.py", line 206, in <module>
    main()
  File "mt_main.py", line 164, in main
    _ = rnn_model.getModel(params, mode='train',reuse=False, buckets=buckets)
  File "/home/parastoo/Desktop/formality/Shakespearizing-Modern-English-master/code/main/mt_solver.py", line 49, in getModel
    pred = self.model_obj.getDecoderModel(config, encoder_outputs, is_training=True, mode='training', reuse=reuse, bucket_num=bucket_num)
  File "/home/parastoo/Desktop/formality/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py", line 402, in getDecoderModel
    pred, sentinel_loss = self.decoderRNN(inp, params, mode='training')  # timesteps, N, vocab_size
  File "/home/parastoo/Desktop/formality/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py", line 313, in decoderRNN
    cur_pred = self.getDecoderOutput(cell_output, lstm_cell_size, token_vocab_size, out_weights, (alpha,sentinel_weight), encoder_input_sequence, batch_size, token_vocab_size, context)
  File "/home/parastoo/Desktop/formality/Shakespearizing-Modern-English-master/code/main/mt_model_pointer.py", line 197, in getDecoderOutput
    r_concat = tf.stack( [r,encoder_input_sequence ], axis=2 ) # batch_size, encoder_length, 2
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 824, in stack
    return gen_array_ops._pack(values, axis=axis, name=name)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1889, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/parastoo/anaconda3/envs/tensorflow1.1/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Shapes of all inputs must match: values[0].shape = [32,25] != values[1].shape = [27,25]`

> Hi,
> Thank you for showing interest in our work.
> Code was written for Tensorflow version 1.1.0 - Please use Tensorflow version 1.1.0 to run the code.

**Comment by harsh19** [comment]
Hi,
Thanks for showing interest in our work.
Originally, the codebase was built and tested using Python 2.7 (https://github.com/harsh19/Shakespearizing-Modern-English#requirements ). Unfortunately, we haven't updated the code to work with Python 3. Could you please try with Python 2 .7 if possible, and let us know if you still face any issues ?
